version: "3.9"

services:

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "7082:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongoexpress:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "7081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
